version: '3'
services:
  postgres:
    image: postgres:11.6
  web:
    restart: always
    env_file:
      - .env
    environment:
      - DJANGO_SECRET_KEY=local
    build: ./
    command: >
      bash -c "python wait_for_postgres.py &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  redis:
    image: redis:6-alpine
    volumes:
      - redis-data:/data
  celery:
    restart: always
    build:
      context: .
    user: root
    command: >
      celery -A CornershopTest.celery worker -B -l info --loglevel=DEBUG --without-gossip --without-mingle --without-heartbeat -Ofair --pool=solo
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      - web

volumes:
  redis-data: {}

